-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 12:19:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movie_review
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_review
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_review` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `movie_review` ;

-- -----------------------------------------------------
-- Table `movie_review`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_review`.`Users` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_review`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_review`.`movie` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `story` TEXT(1024) NULL,
  `buy` VARCHAR(255) NULL,
  `video1` VARCHAR(255) NULL,
  `thumb` VARCHAR(255) NOT NULL,
  `video2` VARCHAR(255) NULL,
  `poster` VARCHAR(255) NOT NULL,
  `advice` VARCHAR(255) NULL,
  `title` VARCHAR(255) NOT NULL,
  `cast` TEXT(1024) NULL,
  `director` VARCHAR(60) NULL,
  `genre` VARCHAR(50) NULL,
  `duration` VARCHAR(50) NULL,
  `release` VARCHAR(30) NULL,
  `availability` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_review`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_review`.`comment` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `movieId` INT NOT NULL,
  `userid` INT NOT NULL,
  `movie` VARCHAR(255) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `review` TEXT(1024) NULL,
  `rating` INT NULL,
  `datePosted` VARCHAR(100) NULL,
  PRIMARY KEY (`_id`),
  INDEX `movieID_idx` (`movieId` ASC) ,
  INDEX `userid_idx` (`userid` ASC) ,
  CONSTRAINT `movieID`
    FOREIGN KEY (`movieId`)
    REFERENCES `movie_review`.`movie` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `movie_review`.`Users` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
